### ISSUE TITLE
Not an issue... but how to create the .dylib and .so files ?

### ISSUE THREAD

**Issue by clabnet** [olegtarasov/CrossplatformNativeTest#1]
Hi Oleg, 
sorry for my ignorance.

How are created the bin files libTestLib.dylib and libTestLib.so ? 
What is the process to create its ?

https://olegtarasov.me/cross-platform-net-core-1
404 page not found

Thank's

Best regards

**Comment by clabnet** [comment]
I found myself.

You wrote : 
The library will have the .dll extension on Windows, .so extension on Linux and .dylib on MacOs. 

I working on windows and obviously the compiler create the .dll and not the .so and not .dylib files.

All run fine.  Thanks to people like you we can learn new things every day.

Ciao

**Comment by olegtarasov** [comment]
Hi @clabnet! It's not very clear from the tutorial, but you need to run same CMake commands on Linux and MacOS in order to get .so and .dylib files. Cross-compiling under Windows may work, but it's much more complicated than just using Linux VM or GitHub Actions.
